tblmrkBuyOrder | CREATE TABLE `tblmrkBuyOrder` (
  `mborID` bigint(20) NOT NULL AUTO_INCREMENT,
  `mborTranId` binary(16) DEFAULT NULL,
  `mborUID` bigint(20) DEFAULT NULL,
  `mborAmt` decimal(29,9) DEFAULT NULL,
  `mborDate` datetime DEFAULT NULL,
  `mborFilled` datetime DEFAULT NULL,
  `mborFillPrice` decimal(29,9) DEFAULT NULL,
  `mborFillAmt` decimal(29,9) DEFAULT NULL,
  `mborFundsSecured` bigint(20) DEFAULT NULL,
  `mborMax` decimal(29,9) DEFAULT NULL,
  `mborTradeCanceled` datetime DEFAULT NULL,
  `mborOrdTxnID` varchar(85) DEFAULT NULL,
  `mborCurrency` varchar(45) DEFAULT NULL,
  `mborToken` varchar(45) DEFAULT NULL,
  `mborUseTradeWallet` int(11) DEFAULT NULL,
  `mborPaymentSent` decimal(29,9) DEFAULT 0.000000000,
  PRIMARY KEY (`mborID`),
  KEY `ndxMborUID` (`mborUID`),
  KEY `ndxMborDate` (`mborDate`),
  KEY `ndxMborAmt` (`mborAmt`),
  KEY `ndxMborMax` (`mborMax`),
  KEY `ndxMborFilled` (`mborFilled`),
  KEY `ndxMborFundsSecured` (`mborFundsSecured`),
  KEY `ndxMborTradeCanceled` (`mborTradeCanceled`),
  KEY `ndxMborOrdTxnID` (`mborOrdTxnID`),
  KEY `ndxMborCurrency` (`mborCurrency`),
  KEY `ndxMborToken` (`mborToken`),
  KEY `idx_mborTranId` (`mborTranId`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

 tblmrkSellOrder | CREATE TABLE `tblmrkSellOrder` (
  `msorID` bigint(20) NOT NULL AUTO_INCREMENT,
  `msorTranId` binary(16) DEFAULT NULL,
  `msorUID` bigint(20) DEFAULT NULL,
  `msorAmtGP` decimal(29,9) DEFAULT NULL,
  `msorDate` datetime DEFAULT NULL,
  `msorAlocByBID` bigint(20) DEFAULT NULL,
  `msorFilled` datetime DEFAULT NULL,
  `msorAllocated` decimal(29,9) DEFAULT 0.000000000,
  `msorGoldSecured` bigint(20) DEFAULT NULL,
  `msorGoldReturned` datetime DEFAULT NULL,
  `msorTradeCanceled` datetime DEFAULT NULL,
  `msorMin` decimal(29,9) DEFAULT NULL,
  `msorPayment` datetime DEFAULT NULL,
  `msorCurrency` varchar(45) DEFAULT NULL,
  `msorToken` varchar(45) DEFAULT NULL,
  `msorTokensSent` decimal(29,9) DEFAULT 0.000000000,
  `msorNSF` datetime DEFAULT NULL,
  `msorUseTradeWallet` int(11) DEFAULT NULL,
  `msorTokReturnQty` decimal(29,9) DEFAULT NULL,
  PRIMARY KEY (`msorID`),
  UNIQUE KEY `uniq_msorTranId` (`msorTranId`),
  KEY `ndxMsorMin` (`msorMin`),
  KEY `ndxMsorUID` (`msorUID`),
  KEY `ndxMsorDate` (`msorDate`),
  KEY `ndxMsorAlocByBID` (`msorAlocByBID`),
  KEY `ndxMsorFilled` (`msorFilled`),
  KEY `ndxMsorAmtGP` (`msorAmtGP`),
  KEY `ndxMsorGoldSecured` (`msorGoldSecured`),
  KEY `ndxMsorGoldReturned` (`msorGoldReturned`),
  KEY `ndxMsorTradeCanceled` (`msorTradeCanceled`),
  KEY `ndxMsorPayment` (`msorPayment`),
  KEY `ndxMsorCurrency` (`msorCurrency`),
  KEY `ndxMsorToken` (`msorToken`),
  KEY `ndxMsorNSF` (`msorNSF`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

 tblmrkFillsLog | CREATE TABLE `tblmrkFillsLog` (
  `mflgID` bigint(20) NOT NULL AUTO_INCREMENT,
  `mflgTranId` binary(16) DEFAULT NULL,
  `mflgBTranId` binary(16) DEFAULT NULL,
  `mflgSTranId` binary(16) DEFAULT NULL,
  `mflgAmtGP` decimal(29,9) DEFAULT NULL,
  `mflgDate` datetime DEFAULT NULL,
  `mflgComplete` datetime DEFAULT NULL,
  `mflgPrice` decimal(29,9) DEFAULT NULL,
  `mflgRedDate` datetime DEFAULT NULL,
  `mflgRedStatus` int(11) DEFAULT NULL,
  `mflgRedMethod` varchar(20) DEFAULT NULL,
  `mflgMVCompleted` datetime DEFAULT NULL,
  `mflgCurrency` varchar(45) DEFAULT NULL,
  `mflgToken` varchar(45) DEFAULT NULL,
  `mflgNSF` datetime DEFAULT NULL,
  `mflgTokensSent` decimal(29,9) DEFAULT NULL,
  `mflgPaymentAmt` decimal(29,9) DEFAULT NULL,
  PRIMARY KEY (`mflgID`),
  KEY `ndxMflgComplete` (`mflgComplete`),
  KEY `ndxMflgDate` (`mflgDate`),
  KEY `ndxMflgBID` (`mflgBTranId`),
  KEY `ndxMflgSID` (`mflgSTranId`),
  KEY `ndxMflgRedDate` (`mflgRedDate`),
  KEY `ndxMflgRedStatus` (`mflgRedStatus`),
  KEY `ndxMflgRedMethod` (`mflgRedMethod`),
  KEY `ndxMflgMVCompleted` (`mflgMVCompleted`),
  KEY `ndxMflgCurrency` (`mflgCurrency`),
  KEY `ndxMflgToken` (`mflgToken`),
  KEY `ndxMflgNSF` (`mflgNSF`),
  KEY `idx_mflgTranId` (`mflgTranId`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
